<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhanQuyenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('phan_quyens')->delete();
        DB::table('phan_quyens')->truncate();

        DB::table('phan_quyens')->insert([
            ['id' => '1', 'id_chuc_nang' => '1', 'id_chuc_vu' => '1'],
            ['id' => '2', 'id_chuc_nang' => '2', 'id_chuc_vu' => '1'],
            ['id' => '3', 'id_chuc_nang' => '3', 'id_chuc_vu' => '1'],
            ['id' => '4', 'id_chuc_nang' => '4', 'id_chuc_vu' => '1'],
            ['id' => '5', 'id_chuc_nang' => '5', 'id_chuc_vu' => '1'],
            ['id' => '6', 'id_chuc_nang' => '6', 'id_chuc_vu' => '1'],
            ['id' => '7', 'id_chuc_nang' => '7', 'id_chuc_vu' => '1'],
            ['id' => '8', 'id_chuc_nang' => '8', 'id_chuc_vu' => '1'],
            ['id' => '9', 'id_chuc_nang' => '9', 'id_chuc_vu' => '1'],
            ['id' => '10', 'id_chuc_nang' => '10', 'id_chuc_vu' => '1'],
            ['id' => '11', 'id_chuc_nang' => '11', 'id_chuc_vu' => '1'],
            ['id' => '12', 'id_chuc_nang' => '12', 'id_chuc_vu' => '1'],
            ['id' => '13', 'id_chuc_nang' => '13', 'id_chuc_vu' => '1'],
            ['id' => '14', 'id_chuc_nang' => '14', 'id_chuc_vu' => '1'],
            ['id' => '15', 'id_chuc_nang' => '15', 'id_chuc_vu' => '1'],
            ['id' => '16', 'id_chuc_nang' => '16', 'id_chuc_vu' => '1'],
            ['id' => '17', 'id_chuc_nang' => '17', 'id_chuc_vu' => '1'],
            ['id' => '18', 'id_chuc_nang' => '18', 'id_chuc_vu' => '1'],
            ['id' => '19', 'id_chuc_nang' => '19', 'id_chuc_vu' => '1'],
            ['id' => '20', 'id_chuc_nang' => '20', 'id_chuc_vu' => '1'],
            ['id' => '21', 'id_chuc_nang' => '21', 'id_chuc_vu' => '1'],
            ['id' => '22', 'id_chuc_nang' => '22', 'id_chuc_vu' => '1'],
            ['id' => '23', 'id_chuc_nang' => '23', 'id_chuc_vu' => '1'],
            ['id' => '24', 'id_chuc_nang' => '24', 'id_chuc_vu' => '1'],
            ['id' => '25', 'id_chuc_nang' => '25', 'id_chuc_vu' => '1'],
            ['id' => '26', 'id_chuc_nang' => '26', 'id_chuc_vu' => '1'],
            ['id' => '27', 'id_chuc_nang' => '27', 'id_chuc_vu' => '1'],
            ['id' => '28', 'id_chuc_nang' => '28', 'id_chuc_vu' => '1'],
            ['id' => '29', 'id_chuc_nang' => '29', 'id_chuc_vu' => '1'],
            ['id' => '30', 'id_chuc_nang' => '30', 'id_chuc_vu' => '1'],
            ['id' => '31', 'id_chuc_nang' => '31', 'id_chuc_vu' => '1'],
            ['id' => '32', 'id_chuc_nang' => '32', 'id_chuc_vu' => '1'],
            ['id' => '33', 'id_chuc_nang' => '33', 'id_chuc_vu' => '1'],
            ['id' => '34', 'id_chuc_nang' => '34', 'id_chuc_vu' => '1'],
            ['id' => '35', 'id_chuc_nang' => '35', 'id_chuc_vu' => '1'],
            ['id' => '36', 'id_chuc_nang' => '36', 'id_chuc_vu' => '1'],
            ['id' => '37', 'id_chuc_nang' => '37', 'id_chuc_vu' => '1'],
            ['id' => '38', 'id_chuc_nang' => '38', 'id_chuc_vu' => '1'],
            ['id' => '39', 'id_chuc_nang' => '39', 'id_chuc_vu' => '1'],
            ['id' => '40', 'id_chuc_nang' => '40', 'id_chuc_vu' => '1'],
            ['id' => '41', 'id_chuc_nang' => '41', 'id_chuc_vu' => '1'],
            ['id' => '42', 'id_chuc_nang' => '42', 'id_chuc_vu' => '1'],
            ['id' => '43', 'id_chuc_nang' => '43', 'id_chuc_vu' => '1'],
            ['id' => '44', 'id_chuc_nang' => '44', 'id_chuc_vu' => '1'],
            ['id' => '45', 'id_chuc_nang' => '45', 'id_chuc_vu' => '1'],
            ['id' => '46', 'id_chuc_nang' => '46', 'id_chuc_vu' => '1'],
            ['id' => '47', 'id_chuc_nang' => '47', 'id_chuc_vu' => '1'],
            ['id' => '48', 'id_chuc_nang' => '48', 'id_chuc_vu' => '1'],
            ['id' => '49', 'id_chuc_nang' => '49', 'id_chuc_vu' => '1'],
            ['id' => '50', 'id_chuc_nang' => '50', 'id_chuc_vu' => '1'],
            ['id' => '51', 'id_chuc_nang' => '51', 'id_chuc_vu' => '1'],
            ['id' => '52', 'id_chuc_nang' => '52', 'id_chuc_vu' => '1'],
            ['id' => '53', 'id_chuc_nang' => '53', 'id_chuc_vu' => '1'],
            ['id' => '54', 'id_chuc_nang' => '54', 'id_chuc_vu' => '1'],
            ['id' => '55', 'id_chuc_nang' => '55', 'id_chuc_vu' => '1'],
            ['id' => '56', 'id_chuc_nang' => '56', 'id_chuc_vu' => '1'],
            ['id' => '57', 'id_chuc_nang' => '57', 'id_chuc_vu' => '1'],
            ['id' => '58', 'id_chuc_nang' => '58', 'id_chuc_vu' => '1'],
            ['id' => '59', 'id_chuc_nang' => '59', 'id_chuc_vu' => '1'],
            ['id' => '60', 'id_chuc_nang' => '60', 'id_chuc_vu' => '1'],
            ['id' => '61', 'id_chuc_nang' => '61', 'id_chuc_vu' => '1'],
            ['id' => '62', 'id_chuc_nang' => '62', 'id_chuc_vu' => '1'],
            ['id' => '63', 'id_chuc_nang' => '63', 'id_chuc_vu' => '1'],
            ['id' => '64', 'id_chuc_nang' => '64', 'id_chuc_vu' => '1'],
            ['id' => '65', 'id_chuc_nang' => '65', 'id_chuc_vu' => '1'],
            ['id' => '66', 'id_chuc_nang' => '66', 'id_chuc_vu' => '1'],
            ['id' => '67', 'id_chuc_nang' => '67', 'id_chuc_vu' => '1'],
            ['id' => '68', 'id_chuc_nang' => '68', 'id_chuc_vu' => '1'],
            ['id' => '69', 'id_chuc_nang' => '69', 'id_chuc_vu' => '1'],
            ['id' => '70', 'id_chuc_nang' => '70', 'id_chuc_vu' => '1'],
            ['id' => '71', 'id_chuc_nang' => '71', 'id_chuc_vu' => '1'],
            ['id' => '72', 'id_chuc_nang' => '72', 'id_chuc_vu' => '1'],
            ['id' => '73', 'id_chuc_nang' => '73', 'id_chuc_vu' => '1'],
            ['id' => '74', 'id_chuc_nang' => '74', 'id_chuc_vu' => '1'],
            ['id' => '75', 'id_chuc_nang' => '75', 'id_chuc_vu' => '1'],
            ['id' => '76', 'id_chuc_nang' => '76', 'id_chuc_vu' => '1'],
            ['id' => '77', 'id_chuc_nang' => '77', 'id_chuc_vu' => '1'],
            ['id' => '78', 'id_chuc_nang' => '78', 'id_chuc_vu' => '1'],
            ['id' => '79', 'id_chuc_nang' => '79', 'id_chuc_vu' => '1'],
            ['id' => '80', 'id_chuc_nang' => '80', 'id_chuc_vu' => '1'],
            ['id' => '81', 'id_chuc_nang' => '81', 'id_chuc_vu' => '1'],
            ['id' => '82', 'id_chuc_nang' => '82', 'id_chuc_vu' => '1'],
            ['id' => '83', 'id_chuc_nang' => '83', 'id_chuc_vu' => '1'],
            ['id' => '84', 'id_chuc_nang' => '84', 'id_chuc_vu' => '1'],
            ['id' => '85', 'id_chuc_nang' => '85', 'id_chuc_vu' => '1'],
            ['id' => '86', 'id_chuc_nang' => '86', 'id_chuc_vu' => '1'],
            ['id' => '87', 'id_chuc_nang' => '87', 'id_chuc_vu' => '1'],
            ['id' => '88', 'id_chuc_nang' => '88', 'id_chuc_vu' => '1'],
            ['id' => '89', 'id_chuc_nang' => '89', 'id_chuc_vu' => '1'],
            ['id' => '90', 'id_chuc_nang' => '90', 'id_chuc_vu' => '1'],
            ['id' => '91', 'id_chuc_nang' => '91', 'id_chuc_vu' => '1'],
            ['id' => '92', 'id_chuc_nang' => '92', 'id_chuc_vu' => '1'],
            ['id' => '93', 'id_chuc_nang' => '93', 'id_chuc_vu' => '1'],
            ['id' => '94', 'id_chuc_nang' => '94', 'id_chuc_vu' => '1'],
            ['id' => '95', 'id_chuc_nang' => '95', 'id_chuc_vu' => '1'],
            ['id' => '96', 'id_chuc_nang' => '96', 'id_chuc_vu' => '1'],
            ['id' => '97', 'id_chuc_nang' => '97', 'id_chuc_vu' => '1'],
            ['id' => '98', 'id_chuc_nang' => '98', 'id_chuc_vu' => '1'],
            ['id' => '99', 'id_chuc_nang' => '99', 'id_chuc_vu' => '1'],
            ['id' => '100', 'id_chuc_nang' => '45', 'id_chuc_vu' => '3'],
            ['id' => '101', 'id_chuc_nang' => '46', 'id_chuc_vu' => '3'],
            ['id' => '102', 'id_chuc_nang' => '47', 'id_chuc_vu' => '3'],
            ['id' => '103', 'id_chuc_nang' => '48', 'id_chuc_vu' => '3'],
            ['id' => '104', 'id_chuc_nang' => '49', 'id_chuc_vu' => '3'],
            ['id' => '105', 'id_chuc_nang' => '50', 'id_chuc_vu' => '3'],
            ['id' => '106', 'id_chuc_nang' => '51', 'id_chuc_vu' => '3'],
            ['id' => '107', 'id_chuc_nang' => '52', 'id_chuc_vu' => '3'],
            ['id' => '108', 'id_chuc_nang' => '53', 'id_chuc_vu' => '3'],
            ['id' => '109', 'id_chuc_nang' => '54', 'id_chuc_vu' => '3'],
            ['id' => '110', 'id_chuc_nang' => '55', 'id_chuc_vu' => '3'],
            ['id' => '111', 'id_chuc_nang' => '56', 'id_chuc_vu' => '3'],
            ['id' => '112', 'id_chuc_nang' => '57', 'id_chuc_vu' => '3'],
            ['id' => '113', 'id_chuc_nang' => '58', 'id_chuc_vu' => '3'],
            ['id' => '114', 'id_chuc_nang' => '59', 'id_chuc_vu' => '3'],
            ['id' => '115', 'id_chuc_nang' => '60', 'id_chuc_vu' => '3'],
            ['id' => '116', 'id_chuc_nang' => '76', 'id_chuc_vu' => '3'],
            ['id' => '117', 'id_chuc_nang' => '77', 'id_chuc_vu' => '3'],
            ['id' => '118', 'id_chuc_nang' => '78', 'id_chuc_vu' => '3'],
            ['id' => '119', 'id_chuc_nang' => '79', 'id_chuc_vu' => '3'],
            ['id' => '120', 'id_chuc_nang' => '80', 'id_chuc_vu' => '3'],
            ['id' => '121', 'id_chuc_nang' => '81', 'id_chuc_vu' => '3'],
            ['id' => '122', 'id_chuc_nang' => '82', 'id_chuc_vu' => '3'],
            ['id' => '123', 'id_chuc_nang' => '83', 'id_chuc_vu' => '3'],
            ['id' => '124', 'id_chuc_nang' => '84', 'id_chuc_vu' => '3'],
            ['id' => '125', 'id_chuc_nang' => '85', 'id_chuc_vu' => '3'],
            ['id' => '126', 'id_chuc_nang' => '86', 'id_chuc_vu' => '3'],
            ['id' => '127', 'id_chuc_nang' => '87', 'id_chuc_vu' => '3'],
            ['id' => '128', 'id_chuc_nang' => '88', 'id_chuc_vu' => '3'],
            ['id' => '129', 'id_chuc_nang' => '89', 'id_chuc_vu' => '3'],
            ['id' => '130', 'id_chuc_nang' => '90', 'id_chuc_vu' => '3'],
            ['id' => '131', 'id_chuc_nang' => '91', 'id_chuc_vu' => '3'],
            ['id' => '132', 'id_chuc_nang' => '92', 'id_chuc_vu' => '3'],
            ['id' => '133', 'id_chuc_nang' => '100', 'id_chuc_vu' => '1'],
            ['id' => '134', 'id_chuc_nang' => '45', 'id_chuc_vu' => '2'],
            ['id' => '135', 'id_chuc_nang' => '46', 'id_chuc_vu' => '2'],
            ['id' => '136', 'id_chuc_nang' => '47', 'id_chuc_vu' => '2'],
            ['id' => '137', 'id_chuc_nang' => '48', 'id_chuc_vu' => '2'],
            ['id' => '138', 'id_chuc_nang' => '49', 'id_chuc_vu' => '2'],
            ['id' => '139', 'id_chuc_nang' => '50', 'id_chuc_vu' => '2'],
            ['id' => '140', 'id_chuc_nang' => '51', 'id_chuc_vu' => '2'],
            ['id' => '141', 'id_chuc_nang' => '52', 'id_chuc_vu' => '2'],
            ['id' => '142', 'id_chuc_nang' => '53', 'id_chuc_vu' => '2'],
            ['id' => '143', 'id_chuc_nang' => '54', 'id_chuc_vu' => '2'],
            ['id' => '144', 'id_chuc_nang' => '55', 'id_chuc_vu' => '2'],
            ['id' => '145', 'id_chuc_nang' => '56', 'id_chuc_vu' => '2'],
            ['id' => '146', 'id_chuc_nang' => '57', 'id_chuc_vu' => '2'],
            ['id' => '147', 'id_chuc_nang' => '58', 'id_chuc_vu' => '2'],
            ['id' => '148', 'id_chuc_nang' => '59', 'id_chuc_vu' => '2'],
            ['id' => '149', 'id_chuc_nang' => '60', 'id_chuc_vu' => '2'],
            ['id' => '150', 'id_chuc_nang' => '62', 'id_chuc_vu' => '2'],
            ['id' => '151', 'id_chuc_nang' => '76', 'id_chuc_vu' => '4'],
            ['id' => '152', 'id_chuc_nang' => '77', 'id_chuc_vu' => '4'],
            ['id' => '153', 'id_chuc_nang' => '78', 'id_chuc_vu' => '4'],
            ['id' => '154', 'id_chuc_nang' => '79', 'id_chuc_vu' => '4'],
            ['id' => '155', 'id_chuc_nang' => '80', 'id_chuc_vu' => '4'],
            ['id' => '156', 'id_chuc_nang' => '81', 'id_chuc_vu' => '4'],
            ['id' => '157', 'id_chuc_nang' => '82', 'id_chuc_vu' => '4'],
            ['id' => '158', 'id_chuc_nang' => '83', 'id_chuc_vu' => '4'],
            ['id' => '159', 'id_chuc_nang' => '84', 'id_chuc_vu' => '4'],
            ['id' => '160', 'id_chuc_nang' => '85', 'id_chuc_vu' => '4'],
            ['id' => '161', 'id_chuc_nang' => '86', 'id_chuc_vu' => '4'],
            ['id' => '162', 'id_chuc_nang' => '87', 'id_chuc_vu' => '4'],
            ['id' => '163', 'id_chuc_nang' => '88', 'id_chuc_vu' => '5'],
            ['id' => '164', 'id_chuc_nang' => '89', 'id_chuc_vu' => '5'],
        ]);
    }
}
